[package]
name = "clp-rust-utils"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-sdk-sqs = { workspace = true }
const_format = { workspace = true }
libzstd-rs-sys = { workspace = true }
non-empty-string = { workspace = true }
num_enum = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true, features = ["reqwest-blocking-client"] }
opentelemetry_sdk = { workspace = true }
regex = { workspace = true }
rmp-serde = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
yaml_serde = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
utoipa = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
