[package]
name = "api-server"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "api_server"
path = "src/lib.rs"

[[bin]]
name = "api_server"
path  = "src/bin/api_server.rs"

[[bin]]
name = "api-server-openapi-codegen"
path = "src/bin/openapi_codegen.rs"

[dependencies]
anyhow = { workspace = true }
async-stream = { workspace = true }
aws-sdk-s3 = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clp-rust-utils = { workspace = true }
futures = { workspace = true }
mongodb = { workspace = true }
num_enum = { workspace = true }
non-empty-string = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
pin-project-lite = { workspace = true }
rmp-serde = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["chrono"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower-http = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true, features = ["axum_extras"] }
utoipa-axum = { workspace = true }

[dev-dependencies]
http-body-util = { workspace = true }
tower = { workspace = true }
