name: "Build CLP Core"
description: "Configures CMake and uses CMake to build CLP Core"

inputs:
  build_type:
    description: "CLP CMake Build Type: Debug, Release, RelWithDebInfo and MinSizeRel"
    required: false
    default: Release
  
  output_path:
    default: ${{github.workspace}}
  
outputs:
  binaries:
    description: "Binaries path"
    value: ${{github.workspace}}/build/clp_binaries.tar

runs:
  using: "composite"
  steps:

    - name: Download submodules
      run: ./tools/scripts/deps-download/download-all.sh
      working-directory: ${{github.workspace}}/components/core
      shell: bash

    # - name: Configure CMake
    #   # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
    #   # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
    #   run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{inputs.build_type}}
    #   working-directory: ${{github.workspace}}/components/core
    #   shell: bash

    # - name: Build
    #   # Build your program with the given configuration
    #   run: cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}}
    #   working-directory: ${{github.workspace}}/components/core
    #   shell: bash

    - run: mkdir -p $GITHUB_WORKSPACE/build && touch $GITHUB_WORKSPACE/build/clp && touch $GITHUB_WORKSPACE/build/clg && touch $GITHUB_WORKSPACE/build/clo && touch $GITHUB_WORKSPACE/build/make-dictionaries-readable
      shell: bash
    
    - name: Bundle Built Binaries
      run: tar -cf $GITHUB_WORKSPACE/clp_binaries.tar $GITHUB_WORKSPACE/build/clp $GITHUB_WORKSPACE/build/clg $GITHUB_WORKSPACE/build/clo $GITHUB_WORKSPACE/build/make-dictionaries-readable
      shell: bash

    - run: echo $GITHUB_WORKSPACE
      shell: bash
  
    - name: Upload CLP Binary artifact
      uses: actions/upload-artifact@main
      with:
        name: clp_binaries_focal
        path: ${{github.workspace}}/clp_binaries.tar
        if-no-files-found: error
