name: "Build CLP Core"
description: "Configures CMake and uses CMake to build CLP Core"

inputs:
  build_type:
    description: "CLP CMake Build Type: Debug, Release, RelWithDebInfo and MinSizeRel"
    required: false
    default: Release
  
outputs:
  binaries:
    description: "Binaries path"
    value: ${{github.workspace}}/build/clp_binaries.tar

runs:
  using: "composite"
  steps:

    # - name: Download submodules
    #   run: ./tools/scripts/deps-download/download-all.sh
    #   working-directory: ${{github.workspace}}/components/core
    #   shell: bash

    # - name: Configure CMake
    #   # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
    #   # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
    #   run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{inputs.build_type}}
    #   working-directory: ${{github.workspace}}/components/core
    #   shell: bash

    # - name: Build
    #   # Build your program with the given configuration
    #   run: cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}}
    #   working-directory: ${{github.workspace}}/components/core
    #   shell: bash

    - run: mkdir -p ${{github.workspace}}/build && touch ${{github.workspace}}/build/clp && ${{github.workspace}}/build/clg && ${{github.workspace}}/build/clo && ${{github.workspace}}/build/make-dictionaries-readable
      shell: bash
    
    - name: Bundle Built Binaries
      run: tar -cf ${{github.workspace}}/build/clp_binaries.tar ${{github.workspace}}/build/clp ${{github.workspace}}/build/clg ${{github.workspace}}/build/clo ${{github.workspace}}/build/make-dictionaries-readable
      shell: bash
    