name: "Build CLP Core"
description: "Configures CMake and uses CMake to build CLP Core"

inputs:
  build_type:
    description: "CLP CMake Build Type: Debug, Release, RelWithDebInfo and MinSizeRel"
    required: false
    default: Release
  cmake_config_extra_args:
    description: "Extra args to pass to CMake during configuration"
    required: false
    default: ""
  
runs:
  using: "composite"
  steps:

    - name: Download submodules
      run: ./tools/scripts/deps-download/download-all.sh
      working-directory: ./components/core
      shell: bash

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory
      run: cmake -B $GITHUB_WORKSPACE/build
                 -DCMAKE_BUILD_TYPE=${{inputs.build_type}} 
                 ${{inputs.cmake_config_extra_args}}
      working-directory: ./components/core
      shell: bash

    - name: Build
      # Build your program with the given configuration
      run: cmake --build $GITHUB_WORKSPACE/build --config ${{inputs.build_type}}
      working-directory: ./components/core
      shell: bash
      
    - name: Bundle Built Binaries
      run: |
        cd $GITHUB_WORKSPACE/build 
        tar -cf $GITHUB_WORKSPACE/clp-binaries-focal.tar ./clp ./clg ./clo ./make-dictionaries-readable
      shell: bash
