extends: "default"

yaml-files:
  - ".clang-format"
  - ".yamllint"
  - "*.yaml"
  - "*.yml"

ignore: |
  .lint-venv/
  components/core/build/
  components/core/cmake-build-debug/
  components/core/cmake-build-release/
  components/core/submodules/
  components/core/third-party/

rules:
  anchors:
    forbid-duplicated-anchors: true
    forbid-unused-anchors: true

  braces:
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  brackets:
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  comments:
    # Disabled so that snippets can be uncommented easily
    require-starting-space: false

  document-end:
    present: false

  document-start:
    present: false

  float-values:
    require-numeral-before-decimal: true

  indentation:
    spaces: 2

  line-length:
    max: 100
    allow-non-breakable-words: false

  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false

  quoted-strings:
    quote-type: "double"

  truthy:
    # Disabled for keys since GitHub actions uses the truthy-looking key "on"
    check-keys: false
