version: "3"

set: ["u", "pipefail"]
shopt: ["globstar"]

includes:
  codegen: "taskfiles/codegen.yaml"
  deps: "taskfiles/deps/main.yaml"
  docker-images: "taskfiles/docker-images.yaml"
  docs: "taskfiles/docs.yaml"
  helm: "taskfiles/helm.yaml"
  lint: "taskfiles/lint.yaml"
  tests: "taskfiles/tests/main.yaml"
  toolchains: "taskfiles/toolchains.yaml"
  utils: "tools/yscope-dev-utils/exports/taskfiles/utils/utils.yaml"

vars:
  # Source paths
  G_COMPONENTS_DIR: "{{.ROOT_DIR}}/components"
  G_CORE_COMPONENT_DIR: "{{.G_COMPONENTS_DIR}}/core"
  G_CORE_COMPONENT_SUBMODULES_DIR: "{{.G_CORE_COMPONENT_DIR}}/submodules"
  G_PYTHON_WHEELS_YSCOPE_CLP_CORE_DIR: "{{.ROOT_DIR}}/python-wheels/yscope-clp-core"
  G_WEBUI_SRC_DIR: "{{.G_COMPONENTS_DIR}}/webui"

  # Build paths
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_CONFIG_SCHEMA_BUILD_DIR: "{{.G_BUILD_DIR}}/config-schema"
  G_CORE_COMPONENT_BUILD_DIR: "{{.G_BUILD_DIR}}/core"
  G_NODEJS_22_BUILD_DIR: "{{.G_BUILD_DIR}}/nodejs-22"
  G_NODEJS_22_BIN_DIR: "{{.G_NODEJS_22_BUILD_DIR}}/bin"
  G_PACKAGE_BUILD_DIR: "{{.G_BUILD_DIR}}/clp-package"
  G_PACKAGE_VENV_DIR: "{{.G_BUILD_DIR}}/package-venv"
  G_PYTHON_LIBS_DIR: "{{.G_BUILD_DIR}}/python-libs"
  G_PYTHON_WHEELS_BUILD_DIR: "{{.G_BUILD_DIR}}/python-wheels"
  G_RUST_BUILD_DIR: "{{.G_BUILD_DIR}}/rust-targets"
  G_SPIDER_BUILD_DIR: "{{.G_BUILD_DIR}}/spider"
  G_WEBUI_BUILD_DIR: "{{.G_BUILD_DIR}}/webui"

  # Taskfile paths
  G_UTILS_TASKFILE: "{{.ROOT_DIR}}/tools/yscope-dev-utils/exports/taskfiles/utils/utils.yaml"

  # Versions
  G_PACKAGE_VERSION: "0.9.1-dev"

  # Build parameters
  # NOTE: Defaulting to an empty string is safe since CMake ignores an empty string.
  G_CPP_MAX_PARALLELISM_PER_BUILD_TASK: >-
    {{default "" (env "CLP_CPP_MAX_PARALLELISM_PER_BUILD_TASK")}}

  # Checksum files
  G_PACKAGE_CHECKSUM_FILE: "{{.G_BUILD_DIR}}/package.md5"
  G_PYTHON_LIBS_CHECKSUM_FILE: "{{.G_BUILD_DIR}}/python-libs.md5"
  G_WEBUI_CHECKSUM_FILE: "{{.G_BUILD_DIR}}/webui.md5"
  G_WEBUI_CLIENT_NODE_MODULES_CHECKSUM_FILE: "{{.G_BUILD_DIR}}/webui-client-node-modules.md5"
  G_WEBUI_COMMON_NODE_MODULES_CHECKSUM_FILE: "{{.G_BUILD_DIR}}/webui-common-node-modules.md5"
  G_WEBUI_LOG_VIEWER_NODE_MODULES_CHECKSUM_FILE:
    "{{.G_BUILD_DIR}}/webui-log-viewer-node-modules.md5"
  G_WEBUI_PACKAGE_NODE_MODULES_CHECKSUM_FILE: "{{.G_BUILD_DIR}}/webui-package-node-modules.md5"
  G_WEBUI_SERVER_NODE_MODULES_CHECKSUM_FILE: "{{.G_BUILD_DIR}}/webui-server-node-modules.md5"

tasks:
  default:
    deps: ["package"]

  clean:
    cmds:
      - "rm -rf '{{.G_BUILD_DIR}}'"
      - task: "clean-python-component"
        vars:
          COMPONENT: "clp-mcp-server"
      - task: "clean-python-component"
        vars:
          COMPONENT: "clp-package-utils"
      - task: "clean-python-component"
        vars:
          COMPONENT: "clp-py-utils"
      - task: "clean-python-component"
        vars:
          COMPONENT: "job-orchestration"
      - task: "clean-rust"
      - task: "clean-webui"
      - task: "tests:integration:cache-clear"

  clean-core:
    cmds:
      - task: "utils:cmake:clean"
        vars:
          BUILD_DIR: "{{.G_CORE_COMPONENT_BUILD_DIR}}"

  clp-json-pkg-tar:
    cmds:
      - task: "package-tar"
        vars:
          FLAVOUR: "json"

  clp-text-pkg-tar:
    cmds:
      - task: "package-tar"
        vars:
          FLAVOUR: "text"

  clean-rust:
    cmds:
      - "rm -rf '{{.G_RUST_BUILD_DIR}}'"

  clean-webui:
    cmds:
      - "rm -rf '{{.G_WEBUI_SRC_DIR}}/node_modules'"
      - "rm -rf '{{.G_WEBUI_SRC_DIR}}/server/node_modules'"
      - "rm -rf '{{.G_WEBUI_SRC_DIR}}/yscope-log-viewer/node_modules'"

  package:
    vars:
      CHECKSUM_FILE: "{{.G_PACKAGE_CHECKSUM_FILE}}"
      OUTPUT_DIR: "{{.G_PACKAGE_BUILD_DIR}}"
    sources:
      - "{{.G_BUILD_DIR}}/clp-package-image.id"
      - "{{.G_CONFIG_SCHEMA_BUILD_DIR}}/clp-config.schema.json"
      - "{{.G_WEBUI_BUILD_DIR}}/client/settings.json"
      - "{{.G_WEBUI_BUILD_DIR}}/server/dist/settings.json"
      - "{{.TASKFILE}}"
      - "components/package-template/src/**/*"
      - "tools/deployment/package/**/*"
    generates: ["{{.CHECKSUM_FILE}}"]
    deps:
      - "docker-images:package"
      - "generate-config-schemas"
      - task: "utils:checksum:validate"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}'"
      - >-
        rsync --archive
        "components/package-template/src/"
        "{{.OUTPUT_DIR}}"
      - >-
        rsync --archive
        "{{.OUTPUT_DIR}}/etc/clp-config.template.json.yaml"
        "{{.OUTPUT_DIR}}/etc/clp-config.yaml"
      - >-
        rsync --archive --mkpath
        "{{.G_CONFIG_SCHEMA_BUILD_DIR}}/"
        "{{.OUTPUT_DIR}}/usr/share/config-schemas/"
      - >-
        rsync --archive --mkpath
        "{{.G_WEBUI_BUILD_DIR}}/client/settings.json"
        "{{.OUTPUT_DIR}}/var/www/webui/client/"
      - >-
        rsync --archive --mkpath
        "{{.G_WEBUI_BUILD_DIR}}/server/dist/settings.json"
        "{{.OUTPUT_DIR}}/var/www/webui/server/dist/"
      - >-
        rsync --archive
        "tools/deployment/package/"
        "{{.OUTPUT_DIR}}"
      - >-
        rsync --archive
        "{{.G_BUILD_DIR}}/clp-package-image.id"
        "{{.OUTPUT_DIR}}"
      - "echo '{{.G_PACKAGE_VERSION}}' > '{{.OUTPUT_DIR}}/VERSION'"
      # This command must be last
      - task: "utils:checksum:compute"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]

  core:
    cmds:
      - task: "core-generate"
      - task: "core-build"

  core-generate:
    internal: true
    sources: &core_source_files
      - "{{.G_DEPS_CPP_CHECKSUM_FILE}}"
      - "{{.G_CORE_COMPONENT_DIR}}/cmake/**/*"
      - "{{.G_CORE_COMPONENT_DIR}}/CMakeLists.txt"
      - "{{.G_CORE_COMPONENT_DIR}}/src/**/*"
      - "{{.TASKFILE}}"
      - "/etc/os-release"
    deps:
      - "codegen:clp-s-generate-parsers"
      - "deps:core"
    cmds:
      - task: "utils:cmake:generate"
        vars:
          BUILD_DIR: "{{.G_CORE_COMPONENT_BUILD_DIR}}"
          SOURCE_DIR: "{{.G_CORE_COMPONENT_DIR}}"

  core-build:
    internal: true
    sources: *core_source_files
    generates:
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clg"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clo"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clp"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clp-s"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/indexer"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/log-converter"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/reducer-server"
    cmds:
      - task: "utils:cmake:build"
        vars:
          BUILD_DIR: "{{.G_CORE_COMPONENT_BUILD_DIR}}"
          JOBS: "{{.G_CPP_MAX_PARALLELISM_PER_BUILD_TASK}}"
          TARGETS: ["clg", "clo", "clp", "clp-s", "indexer", "log-converter", "reducer-server"]

  # NOTE: We rely on cargo for checksumming. It automatically rebuilds when source files change or
  # when a binary is missing.
  rust:
    deps: ["toolchains:rust"]
    dir: "{{.ROOT_DIR}}"
    cmd: |-
      . "{{.G_RUST_TOOLCHAIN_ENV_FILE}}"
      cargo build --release --bins

  clp-mcp-server:
    - task: "uv-component"
      vars:
        COMPONENT: "{{.TASK}}"

  clp-package-utils:
    - task: "uv-component"
      vars:
        COMPONENT: "{{.TASK}}"

  clp-py-utils:
    - task: "uv-component"
      vars:
        COMPONENT: "{{.TASK}}"

  generate-config-schemas:
    vars:
      OUTPUT_DIR: "{{.G_CONFIG_SCHEMA_BUILD_DIR}}"
    cmds:
      - |-
        rm -rf "{{.OUTPUT_DIR}}"
        mkdir -p "{{.OUTPUT_DIR}}"
        ./tools/scripts/generate-config-schemas.py "{{.OUTPUT_DIR}}"

  job-orchestration:
    - task: "uv-component"
      vars:
        COMPONENT: "{{.TASK}}"

  package-build-deps:
    deps:
      - "core"
      - "deps:spider"
      - "init"
      - "python-libs"
      - "rust"
      - "webui"

  webui:
    env:
      NODE_ENV: "production"
    vars:
      CHECKSUM_FILE: "{{.G_WEBUI_CHECKSUM_FILE}}"
      OUTPUT_DIR: "{{.G_WEBUI_BUILD_DIR}}"
    sources:
      - "{{.G_WEBUI_CLIENT_NODE_MODULES_CHECKSUM_FILE}}"
      - "{{.G_WEBUI_COMMON_NODE_MODULES_CHECKSUM_FILE}}"
      - "{{.G_WEBUI_LOG_VIEWER_NODE_MODULES_CHECKSUM_FILE}}"
      - "{{.G_WEBUI_PACKAGE_NODE_MODULES_CHECKSUM_FILE}}"
      - "{{.G_WEBUI_SERVER_NODE_MODULES_CHECKSUM_FILE}}"
      - "{{.TASKFILE}}"
      - "**/*"
      - exclude: "**/dist/**/*"
      - exclude: "**/node_modules/**/*"
    dir: "{{.G_WEBUI_SRC_DIR}}"
    generates: ["{{.CHECKSUM_FILE}}"]
    deps:
      - "init"
      - task: "utils:checksum:validate"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]
      - "webui-node-modules"
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}'"
      - "mkdir -p '{{.OUTPUT_DIR}}'"
      - |-
        cd common
        PATH="{{.G_NODEJS_22_BIN_DIR}}":$PATH npm run build
        rsync -a package.json dist "{{.OUTPUT_DIR}}/common/"
      - for: ["client", "yscope-log-viewer"]
        cmd: |-
          cd "{{.G_WEBUI_SRC_DIR}}/{{.ITEM}}"
          PATH="{{.G_NODEJS_22_BIN_DIR}}":$PATH npm run build -- \
          --emptyOutDir --outDir '{{.OUTPUT_DIR}}/{{.ITEM}}'
      - |-
        cd server
        PATH="{{.G_NODEJS_22_BIN_DIR}}":$PATH npx tsc --outDir '{{.OUTPUT_DIR}}/server/dist'
        rsync -a package.json "{{.OUTPUT_DIR}}/server/"
      - |-
        rsync -a package.json package-lock.json "{{.OUTPUT_DIR}}/"
      - |-
        cd "{{.OUTPUT_DIR}}"
        PATH="{{.G_NODEJS_22_BIN_DIR}}":$PATH npm ci --omit=dev
      - task: "utils:checksum:compute"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]

  nodejs-22:
    internal: true
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.G_NODEJS_22_BUILD_DIR}}"
    run: "once"
    cmds:
      - task: "nodejs"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          NODEJS_VERSION: "v22.20.0"
          OUTPUT_DIR: "{{.OUTPUT_DIR}}"

  download-and-extract-tar:
    internal: true
    label: "{{.TASK}}-{{.TAR_NAME}}"
    vars:
      OUTPUT_TMP_DIR: "{{.OUTPUT_DIR}}-tmp"
      EXTRACTED_DIR: "{{.OUTPUT_TMP_DIR}}/{{.EXTRACTED_DIR_NAME}}"
      TAR_PATH: "{{.OUTPUT_TMP_DIR}}/{{.TAR_NAME}}"
    requires:
      vars: ["CHECKSUM_FILE", "EXTRACTED_DIR_NAME", "TAR_NAME", "OUTPUT_DIR", "URL_PREFIX"]
    sources: ["{{.TASKFILE}}"]
    generates: ["{{.CHECKSUM_FILE}}"]
    deps:
      - "init"
      - task: "utils:checksum:validate"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}' '{{.OUTPUT_TMP_DIR}}'"
      - "mkdir -p '{{.OUTPUT_TMP_DIR}}'"
      - >-
        curl --fail --location --show-error
        "{{trimSuffix "/" .URL_PREFIX}}/{{.TAR_NAME}}"
        --output "{{.TAR_PATH}}"
      - "tar xf '{{.TAR_PATH}}' --directory '{{.OUTPUT_TMP_DIR}}'"
      - "mv '{{.EXTRACTED_DIR}}' '{{.OUTPUT_DIR}}'"
      - "rm -rf '{{.OUTPUT_TMP_DIR}}'"
      # This command must be last
      - task: "utils:checksum:compute"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]

  # NOTE: The webui has three different node_modules directories, and we generate a checksum file
  # for each one. The directories are:
  # * server
  # * log-viewer submodule
  # * the top-level one we call "package"
  webui-node-modules:
    internal: true
    vars:
      SRC_DIR: "{{.TASKFILE_DIR}}/components/webui"
      LOG_VIEWER_OUTPUT_DIR: "{{.SRC_DIR}}/yscope-log-viewer/node_modules"
      PACKAGE_OUTPUT_DIR: "{{.SRC_DIR}}/node_modules"
      SERVER_OUTPUT_DIR: "{{.SRC_DIR}}/server/node_modules"
    sources:
      - "{{.G_DEPS_LOG_VIEWER_CHECKSUM_FILE}}"
      - "{{.G_BUILD_DIR}}/nodejs-22.md5"
      - "{{.TASKFILE}}"
      - "**/{,client,common,server,yscope-log-viewer}/package.json"
      - "**/{,client,common,server,yscope-log-viewer}/package-lock.json"
    dir: "{{.SRC_DIR}}"
    generates:
      - "{{.G_WEBUI_LOG_VIEWER_NODE_MODULES_CHECKSUM_FILE}}"
      - "{{.G_WEBUI_PACKAGE_NODE_MODULES_CHECKSUM_FILE}}"
      - "{{.G_WEBUI_SERVER_NODE_MODULES_CHECKSUM_FILE}}"
    deps:
      - "deps:log-viewer"
      - "nodejs-22"
      - task: "utils:checksum:validate"
        vars:
          CHECKSUM_FILE: "{{.G_WEBUI_LOG_VIEWER_NODE_MODULES_CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.LOG_VIEWER_OUTPUT_DIR}}"]
      - task: "utils:checksum:validate"
        vars:
          CHECKSUM_FILE: "{{.G_WEBUI_PACKAGE_NODE_MODULES_CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.PACKAGE_OUTPUT_DIR}}"]
      - task: "utils:checksum:validate"
        vars:
          CHECKSUM_FILE: "{{.G_WEBUI_SERVER_NODE_MODULES_CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.SERVER_OUTPUT_DIR}}"]
    cmds:
      - task: "clean-webui"
      - "PATH='{{.G_NODEJS_22_BIN_DIR}}':$PATH npm run init"
      - |-
        cd yscope-log-viewer
        PATH="{{.G_NODEJS_22_BIN_DIR}}":$PATH npm clean-install
      # These commands must be last
      - task: "utils:checksum:compute"
        vars:
          CHECKSUM_FILE: "{{.G_WEBUI_LOG_VIEWER_NODE_MODULES_CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.LOG_VIEWER_OUTPUT_DIR}}"]
      - task: "utils:checksum:compute"
        vars:
          CHECKSUM_FILE: "{{.G_WEBUI_PACKAGE_NODE_MODULES_CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.PACKAGE_OUTPUT_DIR}}"]
      - task: "utils:checksum:compute"
        vars:
          CHECKSUM_FILE: "{{.G_WEBUI_SERVER_NODE_MODULES_CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.SERVER_OUTPUT_DIR}}"]

  nodejs:
    internal: true
    vars:
      NODEJS_ARCH: "{{ if eq ARCH \"arm64\" }}arm64{{ else }}x64{{ end }}"
      NODEJS_VERSION_BASE_URL: "https://nodejs.org/dist/{{.NODEJS_VERSION}}/"
      NODEJS_FILE_BASE_NAME:
        sh: >-
          curl --header "Cache-Control: no-cache, no-store" --silent "{{.NODEJS_VERSION_BASE_URL}}"
          | grep
          --only-matching
          --max-count 1
          "node-v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+-{{OS}}-{{.NODEJS_ARCH}}"
          | head --lines 1
    requires:
      vars: ["CHECKSUM_FILE", "NODEJS_VERSION", "OUTPUT_DIR"]
    deps: ["init"]
    cmds:
      - task: "download-and-extract-tar"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          TAR_NAME: "{{.NODEJS_FILE_BASE_NAME}}.tar.xz"
          EXTRACTED_DIR_NAME: "{{.NODEJS_FILE_BASE_NAME}}"
          URL_PREFIX: "{{.NODEJS_VERSION_BASE_URL}}"
          OUTPUT_DIR: "{{.OUTPUT_DIR}}"

  package-tar:
    internal: true
    vars:
      VERSIONED_PACKAGE_NAME:
        sh: "echo clp-{{.FLAVOUR}}-$(arch)-v{{.G_PACKAGE_VERSION}}"
      OUTPUT_DIR: "{{.G_BUILD_DIR}}/{{.VERSIONED_PACKAGE_NAME}}"
      OUTPUT_FILE: "{{.OUTPUT_DIR}}.tar.gz"
    requires:
      vars: ["FLAVOUR"]
    sources:
      - "{{.G_BUILD_DIR}}/package.md5"
      - "{{.TASKFILE}}"
    dir: "{{.G_BUILD_DIR}}"
    generates:
      - "{{.VERSIONED_PACKAGE_NAME}}.tar.gz"
    deps: ["package"]
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}' '{{.OUTPUT_FILE}}'"
      # NOTE: The trailing slash after the source is necessary so that rsync copies
      # `/parents/A` -> `/parents/B` rather than `/parents/A` -> `/parents/B/A`
      - "rsync --archive '{{.G_PACKAGE_BUILD_DIR}}/' '{{.OUTPUT_DIR}}'"

      # Apply the config template for the selected FLAVOUR
      - >-
        mv
        "{{.OUTPUT_DIR}}/etc/clp-config.template.{{.FLAVOUR}}.yaml"
        "{{.OUTPUT_DIR}}/etc/clp-config.yaml"
      - "rm {{.OUTPUT_DIR}}/etc/clp-config.template.*.yaml"

      - >-
        tar czf '{{.OUTPUT_FILE}}'
        --directory '{{.G_BUILD_DIR}}'
        --dereference '{{.VERSIONED_PACKAGE_NAME}}'

  python-libs:
    internal: true
    vars:
      CHECKSUM_FILE: "{{.G_PYTHON_LIBS_CHECKSUM_FILE}}"
      OUTPUT_DIR: "{{.G_PYTHON_LIBS_DIR}}"
    sources:
      - "{{.G_BUILD_DIR}}/package-venv.md5"
      - "{{.TASKFILE}}"
      - "components/clp-mcp-server/dist/*.whl"
      - "components/clp-package-utils/dist/*.whl"
      - "components/clp-py-utils/dist/*.whl"
      - "components/job-orchestration/dist/*.whl"
    generates: ["{{.CHECKSUM_FILE}}"]
    deps:
      - "clp-mcp-server"
      - "clp-package-utils"
      - "clp-py-utils"
      - "init"
      - "job-orchestration"
      - "package-venv"
      - task: "utils:checksum:validate"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}'"
      - "mkdir -p '{{.OUTPUT_DIR}}'"
      - |-
        . "{{.G_PACKAGE_VENV_DIR}}/bin/activate"
        pip3 install --upgrade \
          components/clp-mcp-server/dist/*.whl \
          components/clp-package-utils/dist/*.whl \
          components/clp-py-utils/dist/*.whl \
          components/job-orchestration/dist/*.whl \
          -t "{{.OUTPUT_DIR}}"
      - task: "utils:checksum:compute"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]

  package-venv:
    internal: true
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.G_PACKAGE_VENV_DIR}}"
    sources:
      - "{{.ROOT_DIR}}/requirements.txt"
      - "{{.TASKFILE}}"
      - "/etc/os-release"
    generates: ["{{.CHECKSUM_FILE}}"]
    deps:
      - "init"
      - task: "utils:checksum:validate"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]
    cmds:
      - task: "utils:misc:create-venv"
        vars:
          LABEL: "package"
          OUTPUT_DIR: "{{.OUTPUT_DIR}}"
          REQUIREMENTS_FILE: "{{.ROOT_DIR}}/requirements.txt"
      # This command must be last
      - task: "utils:checksum:compute"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]

  uv-component:
    internal: true
    label: "{{.COMPONENT}}"
    requires:
      vars: ["COMPONENT"]
    sources:
      - "{{.TASKFILE}}"
      - "/etc/os-release"
      - "**/*"
      - exclude: "dist/**/*"
    dir: "components/{{.COMPONENT}}"
    generates:
      - "dist/*.whl"
    cmds:
      - task: "clean-python-component"
        vars:
          COMPONENT: "{{.COMPONENT}}"
      - "uv build --wheel --no-cache -o dist"

  clean-python-component:
    internal: true
    label: "clean-{{.COMPONENT}}"
    requires:
      vars: ["COMPONENT"]
    dir: "components/{{.COMPONENT}}"
    cmds:
      - "rm -rf dist"

  init:
    internal: true
    silent: true
    run: "once"
    cmd: "mkdir -p '{{.G_BUILD_DIR}}'"

  python-wheels-yscope-clp-core:
    vars:
      TMP_DIR: "{{.G_BUILD_DIR}}/tmp-{{.TASK}}"
    dir: "{{.G_PYTHON_WHEELS_YSCOPE_CLP_CORE_DIR}}"
    deps: ["core"]
    cmds:
      - "mkdir -p '{{.TMP_DIR}}'"
      - defer: "rm -rf '{{.TMP_DIR}}'"

      # Build the wheel into the temporary directory
      - |-
        export YSCOPE_CLP_CORE_CLP_S_EXE="{{.G_CORE_COMPONENT_BUILD_DIR}}/clp-s"
        uv run --no-cache python3 -m build --wheel --outdir "{{.TMP_DIR}}"

      # Repair the wheel and place it in the final build directory.
      - |-
        uv run --no-cache \
          auditwheel repair "{{.TMP_DIR}}"/*.whl --wheel-dir "{{.G_PYTHON_WHEELS_BUILD_DIR}}"
