version: "3"

includes:
  docs: "docs/tasks.yml"
  lint: "lint-tasks.yml"
  utils: "tools/yscope-dev-utils/taskfiles/utils.yml"

vars:
  # Paths
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_CORE_COMPONENT_BUILD_DIR: "{{.G_BUILD_DIR}}/core"
  G_LATEST_NODEJS_DIR: "{{.G_BUILD_DIR}}/nodejs-latest"
  G_METEOR_BUILD_DIR: "{{.G_BUILD_DIR}}/meteor"
  G_PACKAGE_BUILD_DIR: "{{.G_BUILD_DIR}}/clp-package"
  G_PACKAGE_VENV_DIR: "{{.G_BUILD_DIR}}/package-venv"
  G_WEBUI_BUILD_DIR: "{{.G_BUILD_DIR}}/webui"
  G_WEBUI_NODEJS_BUILD_DIR: "{{.G_BUILD_DIR}}/webui-nodejs"
  G_WEBUI_NODEJS_BIN_DIR: "{{.G_WEBUI_NODEJS_BUILD_DIR}}/bin"

  # Versions
  G_PACKAGE_VERSION: "0.2.0-dev"

tasks:
  default:
    deps: ["package"]

  clean:
    cmds:
      - "rm -rf '{{.G_BUILD_DIR}}'"
      - task: "clean-log-viewer-webui"
      - task: "clean-python-component"
        vars:
          COMPONENT: "clp-package-utils"
      - task: "clean-python-component"
        vars:
          COMPONENT: "clp-py-utils"
      - task: "clean-python-component"
        vars:
          COMPONENT: "job-orchestration"
      - task: "clean-webui"

  clean-log-viewer-webui:
    cmds:
      - "rm -rf 'components/log-viewer-webui/client/node_modules'"
      - "rm -rf 'components/log-viewer-webui/node_modules'"
      - "rm -rf 'components/log-viewer-webui/server/node_modules'"

  clean-webui:
    cmds:
      - "rm -rf 'components/webui/.meteor/local'"
      - "rm -rf 'components/webui/node_modules'"

  clp-json-pkg-tar:
    cmds:
      - task: "package-tar"
        vars:
          FLAVOUR: "json"
          STORAGE_ENGINE: "clp-s"

  clp-text-pkg-tar:
    cmds:
      - task: "package-tar"
        vars:
          FLAVOUR: "text"
          STORAGE_ENGINE: "clp"

  package:
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.G_PACKAGE_BUILD_DIR}}"
    deps:
      - "core"
      - "clp-package-utils"
      - "clp-py-utils"
      - "init"
      - "job-orchestration"
      - "package-venv"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_DIR: "{{.OUTPUT_DIR}}"
      - "webui"
      - "webui-nodejs"
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}'"
      - "rsync -a components/package-template/src/ '{{.OUTPUT_DIR}}'"
      - "rsync --copy-links /etc/os-release '{{.OUTPUT_DIR}}/etc/os-release'"
      - "mkdir -p '{{.OUTPUT_DIR}}/lib/python3/site-packages'"
      - |-
        . "{{.G_PACKAGE_VENV_DIR}}/bin/activate"
        pip3 install --upgrade \
          components/clp-package-utils/dist/*.whl \
          components/clp-py-utils/dist/*.whl \
          components/job-orchestration/dist/*.whl \
          -t "{{.OUTPUT_DIR}}/lib/python3/site-packages"
      - "mkdir -p '{{.OUTPUT_DIR}}/bin'"
      - >-
        rsync -a
        "{{.G_CORE_COMPONENT_BUILD_DIR}}/clg"
        "{{.G_CORE_COMPONENT_BUILD_DIR}}/clo"
        "{{.G_CORE_COMPONENT_BUILD_DIR}}/clp"
        "{{.G_CORE_COMPONENT_BUILD_DIR}}/clp-s"
        "{{.G_CORE_COMPONENT_BUILD_DIR}}/reducer-server"
        "{{.G_WEBUI_NODEJS_BIN_DIR}}/node"
        "{{.OUTPUT_DIR}}/bin/"
      - "mkdir -p '{{.OUTPUT_DIR}}/var/www/'"
      - >-
        rsync -a
        "{{.G_WEBUI_BUILD_DIR}}/"
        "{{.OUTPUT_DIR}}/var/www/"
      - |-
        cd "{{.OUTPUT_DIR}}/var/www/programs/server"
        PATH="{{.G_WEBUI_NODEJS_BIN_DIR}}":$PATH npm install
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"
    sources:
      - "{{.G_BUILD_DIR}}/package-venv.md5"
      - "{{.G_BUILD_DIR}}/webui.md5"
      - "{{.G_BUILD_DIR}}/webui-nodejs.md5"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clg"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clo"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clp"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clp-s"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/reducer-server"
      - "{{.TASKFILE}}"
      - "/etc/os-release"
      - "components/clp-package-utils/dist/*.whl"
      - "components/clp-py-utils/dist/*.whl"
      - "components/job-orchestration/dist/*.whl"
      - "components/package-template/src/**/*"
    generates: ["{{.CHECKSUM_FILE}}"]

  core:
    deps: ["core-submodules", "init"]
    vars:
      SRC_DIR: "components/core"
    cmds:
      - "mkdir -p '{{.G_CORE_COMPONENT_BUILD_DIR}}'"
      - "cmake -S '{{.SRC_DIR}}' -B '{{.G_CORE_COMPONENT_BUILD_DIR}}'"
      - >-
        cmake
        --build "{{.G_CORE_COMPONENT_BUILD_DIR}}"
        --parallel
        --target clg clo clp clp-s reducer-server
    sources:
      - "{{.G_BUILD_DIR}}/core-submodules.md5"
      - "{{.SRC_DIR}}/cmake/**/*"
      - "{{.SRC_DIR}}/CMakeLists.txt"
      - "{{.SRC_DIR}}/src/**/*"
      - "{{.TASKFILE}}"
      - "/etc/os-release"
    generates:
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clg"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clo"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clp"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/clp-s"
      - "{{.G_CORE_COMPONENT_BUILD_DIR}}/reducer-server"

  clp-package-utils:
    - task: "python-component"
      vars:
        COMPONENT: "{{.TASK}}"

  clp-py-utils:
    - task: "python-component"
      vars:
        COMPONENT: "{{.TASK}}"

  job-orchestration:
    - task: "python-component"
      vars:
        COMPONENT: "{{.TASK}}"

  webui:
    deps:
      - "init"
      - "meteor"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_DIR: "{{.OUTPUT_DIR}}"
      - "webui-node-modules"
    dir: "components/webui"
    platforms: ["386", "amd64"]
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.G_WEBUI_BUILD_DIR}}"
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}'"
      - "mkdir -p '{{.OUTPUT_DIR}}'"
      - "PATH='{{.G_METEOR_BUILD_DIR}}':$PATH meteor build --directory '{{.OUTPUT_DIR}}'"
      - >-
        rsync -a
        "{{.OUTPUT_DIR}}/bundle/"
        launcher.js
        settings.json
        "{{.OUTPUT_DIR}}/"
      - "rm -rf '{{.OUTPUT_DIR}}/bundle/'"
      # Remove temp files generated by `meteor build` before checksum
      - "find node_modules -type f -name '.meteor-portable-2.json' -exec rm {} +"
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"
    sources:
      - "{{.G_BUILD_DIR}}/meteor.md5"
      - "{{.G_BUILD_DIR}}/webui-node-modules.md5"
      - "{{.TASKFILE}}"
      - "*"
      - ".meteor/*"
      - "client/**/*"
      - "imports/**/*"
      - "server/**/*"
      - "tests/**/*"
    generates: ["{{.CHECKSUM_FILE}}"]

  nodejs-latest:
    internal: true
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.G_LATEST_NODEJS_DIR}}"
    run: "once"
    cmds:
      - task: "nodejs"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          NODEJS_VERSION: "latest"
          OUTPUT_DIR: "{{.OUTPUT_DIR}}"

  webui-nodejs:
    internal: true
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.G_WEBUI_NODEJS_BUILD_DIR}}"
    cmds:
      - task: "nodejs"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          NODEJS_VERSION: "v14.21.3"
          OUTPUT_DIR: "{{.OUTPUT_DIR}}"

  core-submodules:
    internal: true
    dir: "components/core"
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "submodules"
    deps:
      - "init"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_DIR: "{{.OUTPUT_DIR}}"
    cmds:
      - "tools/scripts/deps-download/download-all.sh"
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"
    sources:
      - "{{.TASKFILE}}"
      - ".gitmodules"
      - "tools/scripts/deps-download/**/*"
    generates: ["{{.CHECKSUM_FILE}}"]

  download-and-extract-tar:
    internal: true
    requires:
      vars: ["CHECKSUM_FILE", "EXTRACTED_DIR_NAME", "TAR_NAME", "OUTPUT_DIR", "URL_PREFIX"]
    label: "{{.TASK}}-{{.TAR_NAME}}"
    vars:
      OUTPUT_TMP_DIR: "{{.OUTPUT_DIR}}-tmp"
      EXTRACTED_DIR: "{{.OUTPUT_TMP_DIR}}/{{.EXTRACTED_DIR_NAME}}"
      TAR_PATH: "{{.OUTPUT_TMP_DIR}}/{{.TAR_NAME}}"
    deps:
      - "init"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_DIR: "{{.OUTPUT_DIR}}"
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}' '{{.OUTPUT_TMP_DIR}}'"
      - "mkdir -p '{{.OUTPUT_TMP_DIR}}'"
      - >-
        curl --fail --location --show-error
        "{{.URL_PREFIX}}/{{.TAR_NAME}}"
        --output "{{.TAR_PATH}}"
      - "tar xf '{{.TAR_PATH}}' --directory '{{.OUTPUT_TMP_DIR}}'"
      - "mv '{{.EXTRACTED_DIR}}' '{{.OUTPUT_DIR}}'"
      - "rm -rf '{{.OUTPUT_TMP_DIR}}'"
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"
    sources: ["{{.TASKFILE}}"]
    generates: ["{{.CHECKSUM_FILE}}"]

  # NOTE: The log-viewer-webui has three different node_modules directories (client, server, and the
  # top-level one we call "package"), meaning we have to create three different checksums. To allow
  # tasks which depend on this task to only have to check one checksum file, we concatenate the
  # three checksum files into one.
  log-viewer-webui-node-modules:
    internal: true
    vars:
      # Checksum files
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      CLIENT_CHECKSUM_FILE: "{{.G_BUILD_DIR}}/log-viewer-webui-client-node-modules.md5"
      PACKAGE_CHECKSUM_FILE: "{{.G_BUILD_DIR}}/log-viewer-webui-package-node-modules.md5"
      SERVER_CHECKSUM_FILE: "{{.G_BUILD_DIR}}/log-viewer-webui-server-node-modules.md5"

      # Directories
      SRC_DIR: "{{.TASKFILE_DIR}}/components/log-viewer-webui"
      CLIENT_OUTPUT_DIR: "{{.SRC_DIR}}/client/node_modules"
      PACKAGE_OUTPUT_DIR: "{{.SRC_DIR}}/node_modules"
      SERVER_OUTPUT_DIR: "{{.SRC_DIR}}/server/node_modules"
    dir: "{{.SRC_DIR}}"
    deps:
      - "nodejs-latest"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CLIENT_CHECKSUM_FILE}}"
          DATA_DIR: "{{.CLIENT_OUTPUT_DIR}}"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.SERVER_CHECKSUM_FILE}}"
          DATA_DIR: "{{.SERVER_OUTPUT_DIR}}"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.PACKAGE_CHECKSUM_FILE}}"
          DATA_DIR: "{{.PACKAGE_OUTPUT_DIR}}"
    cmds:
      - "rm -f {{.CHECKSUM_FILE}}"
      - task: "clean-log-viewer-webui"
      - "PATH='{{.G_LATEST_NODEJS_DIR}}/bin':$PATH npm run init"
      # These commands must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.CLIENT_OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.CLIENT_CHECKSUM_FILE}}"
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.PACKAGE_OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.PACKAGE_CHECKSUM_FILE}}"
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.SERVER_OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.SERVER_CHECKSUM_FILE}}"
      # This command must be last
      - >-
        cat "{{.CLIENT_CHECKSUM_FILE}}" "{{.PACKAGE_CHECKSUM_FILE}}" "{{.SERVER_CHECKSUM_FILE}}"
        > "{{.CHECKSUM_FILE}}"
    sources:
      - "{{.G_BUILD_DIR}}/nodejs-latest.md5"
      - "{{.TASKFILE}}"
      - "client/package.json"
      - "client/package-lock.json"
      - "package.json"
      - "package-lock.json"
      - "server/package.json"
      - "server/package-lock.json"
    generates:
      - "{{.CHECKSUM_FILE}}"
      - "{{.CLIENT_CHECKSUM_FILE}}"
      - "{{.PACKAGE_CHECKSUM_FILE}}"
      - "{{.SERVER_CHECKSUM_FILE}}"

  meteor:
    run: "once"
    preconditions:
      - sh: >-
          (test "$(uname -m)" != "aarch64") || (test "$(uname -s)" != "Linux")
        msg: "Meteor 2.x does not support aarch64 on Linux"
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      METEOR_ARCH: "{{ if eq ARCH \"arm64\" }}arm64{{ else }}x86_64{{ end }}"
      METEOR_PLATFORM: "{{ if eq OS \"darwin\" }}osx{{ else }}linux{{ end }}"
      METEOR_RELEASE: "2.15"
    cmds:
      - task: "download-and-extract-tar"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          EXTRACTED_DIR_NAME: ".meteor"
          OUTPUT_DIR: "{{.G_METEOR_BUILD_DIR}}"
          TAR_NAME: "meteor-bootstrap-os.{{.METEOR_PLATFORM}}.{{.METEOR_ARCH}}.tar.gz"
          URL_PREFIX: "https://static.meteor.com/packages-bootstrap/{{.METEOR_RELEASE}}"

  nodejs:
    internal: true
    deps: ["init"]
    requires:
      vars: ["CHECKSUM_FILE", "NODEJS_VERSION", "OUTPUT_DIR"]
    vars:
      NODEJS_ARCH: "{{ if eq ARCH \"arm64\" }}arm64{{ else }}x64{{ end }}"
      NODEJS_VERSION_BASE_URL: "https://nodejs.org/dist/{{.NODEJS_VERSION}}/"
      NODEJS_FILE_BASE_NAME:
        sh: >-
          curl --header "Cache-Control: no-cache, no-store" --silent "{{.NODEJS_VERSION_BASE_URL}}"
          | grep
          --only-matching
          --max-count 1
          "node-v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+-{{OS}}-{{.NODEJS_ARCH}}"
          | head --lines 1
    cmds:
      - task: "download-and-extract-tar"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          TAR_NAME: "{{.NODEJS_FILE_BASE_NAME}}.tar.xz"
          EXTRACTED_DIR_NAME: "{{.NODEJS_FILE_BASE_NAME}}"
          URL_PREFIX: "{{.NODEJS_VERSION_BASE_URL}}"
          OUTPUT_DIR: "{{.OUTPUT_DIR}}"

  package-tar:
    internal: true
    requires:
      vars: ["FLAVOUR", "STORAGE_ENGINE"]
    vars:
      VERSIONED_PACKAGE_NAME:
        sh: |
          source /etc/os-release
          echo "clp-{{.FLAVOUR}}-${ID}-${VERSION_CODENAME}-$(arch)-v{{.G_PACKAGE_VERSION}}"
      OUTPUT_DIR: "{{.G_BUILD_DIR}}/{{.VERSIONED_PACKAGE_NAME}}"
      OUTPUT_FILE: "{{.OUTPUT_DIR}}.tar.gz"
    dir: "{{.G_BUILD_DIR}}"
    deps: ["package"]
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}' '{{.OUTPUT_FILE}}'"
      # NOTE: The trailing slash after the source is necessary so that rsync copies
      # `/parents/A` -> `/parents/B` rather than `/parents/A` -> `/parents/B/A`
      - "rsync --archive '{{.G_PACKAGE_BUILD_DIR}}/' '{{.OUTPUT_DIR}}'"
      # Set the storage engine for the package
      - task: "utils:replace-text"
        vars:
          FILE_PATH: "{{.OUTPUT_DIR}}/lib/python3/site-packages/clp_py_utils/clp_config.py"
          SED_EXP: >-
            s/([[:space:]]*storage_engine: str = ")[^"]+"/\1{{.STORAGE_ENGINE}}"/
      - task: "utils:replace-text"
        vars:
          FILE_PATH: "{{.OUTPUT_DIR}}/etc/clp-config.yml"
          SED_EXP: >-
            s/(\#[[:space:]]*storage_engine: ")[^"]+"/\1{{.STORAGE_ENGINE}}"/
      - >-
        tar czf '{{.OUTPUT_FILE}}'
        --directory '{{.G_BUILD_DIR}}'
        --dereference '{{.VERSIONED_PACKAGE_NAME}}'
    sources:
      - "{{.G_BUILD_DIR}}/package.md5"
      - "{{.TASKFILE}}"
    generates:
      - "{{.VERSIONED_PACKAGE_NAME}}.tar.gz"

  package-venv:
    internal: true
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.G_PACKAGE_VENV_DIR}}"
    deps:
      - "init"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_DIR: "{{.OUTPUT_DIR}}"
    cmds:
      - task: "utils:create-venv"
        vars:
          LABEL: "package"
          OUTPUT_DIR: "{{.OUTPUT_DIR}}"
          REQUIREMENTS_FILE: "requirements.txt"
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"
    sources:
      - "{{.ROOT_DIR}}/requirements.txt"
      - "{{.TASKFILE}}"
      - "/etc/os-release"
    generates: ["{{.CHECKSUM_FILE}}"]

  python-component:
    internal: true
    requires:
      vars: ["COMPONENT"]
    label: "{{.COMPONENT}}"
    deps:
      - task: "component-venv"
        vars:
          COMPONENT: "{{.COMPONENT}}"
          OUTPUT_DIR: "{{.VENV_DIR}}"
    vars:
      PACKAGE:
        sh: "echo {{.COMPONENT}} | tr - _"
      VENV_DIR: "{{.G_BUILD_DIR}}/{{.COMPONENT}}/venv"
    dir: "components/{{.COMPONENT}}"
    cmds:
      - task: "clean-python-component"
        vars:
          COMPONENT: "{{.COMPONENT}}"
      - |-
        . "{{.VENV_DIR}}/bin/activate"
        poetry build --format wheel
    sources:
      - "{{.G_BUILD_DIR}}/{{.COMPONENT}}_venv.md5"
      - "{{.PACKAGE}}/**/*"
      - "{{.ROOT_DIR}}/requirements.txt"
      - "{{.TASKFILE}}"
      - "/etc/os-release"
      - "pyproject.toml"
    generates:
      - "dist/*.whl"

  webui-node-modules:
    internal: true
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      WEBUI_SRC_DIR: "{{.ROOT_DIR}}/components/webui"
      OUTPUT_DIR: "{{.WEBUI_SRC_DIR}}/node_modules"
    dir: "{{.WEBUI_SRC_DIR}}"
    deps:
      - "init"
      - "meteor"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_DIR: "{{.OUTPUT_DIR}}"
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}'"
      - "PATH='{{.G_METEOR_BUILD_DIR}}':$PATH meteor npm install --production"
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"
    sources:
      - "{{.G_BUILD_DIR}}/meteor.md5"
      - "{{.TASKFILE}}"
      - ".meteor/packages"
      - "package.json"
    generates: ["{{.CHECKSUM_FILE}}"]

  component-venv:
    internal: true
    requires:
      vars: ["COMPONENT", "OUTPUT_DIR"]
    label: "{{.COMPONENT}}-venv"
    dir: "components/{{.COMPONENT}}"
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.COMPONENT}}-venv.md5"
    deps:
      - "init"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_DIR: "{{.OUTPUT_DIR}}"
    cmds:
      - task: "utils:create-venv"
        vars:
          LABEL: "{{.COMPONENT}}"
          OUTPUT_DIR: "{{.OUTPUT_DIR}}"
          REQUIREMENTS_FILE: "{{.ROOT_DIR}}/requirements.txt"
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"
    sources:
      - "{{.ROOT_DIR}}/requirements.txt"
      - "{{.TASKFILE}}"
      - "/etc/os-release"
      - "pyproject.toml"
    generates: ["{{.CHECKSUM_FILE}}"]

  clean-python-component:
    internal: true
    requires:
      vars: ["COMPONENT"]
    label: "clean-{{.COMPONENT}}"
    dir: "components/{{.COMPONENT}}"
    cmds:
      - "rm -rf dist"

  init:
    internal: true
    run: "once"
    silent: true
    cmd: "mkdir -p '{{.G_BUILD_DIR}}'"
