{{- if .Values.clpConfig.aws_config }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "clp.fullname" . }}-aws-config
  labels:
    {{- include "clp.labels" . | nindent 4 }}
stringData:
  {{- with .Values.clpConfig.aws_config.credentials }}
  credentials: {{ . | quote }}
  {{- end }}
  {{- with .Values.clpConfig.aws_config.config }}
  config: {{ . | quote }}
  {{- end }}
{{- end }}
