apiVersion: "batch/v1"
kind: "Job"
metadata:
  name: {{ include "clp.fullname" . }}-db-table-creator
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "db-table-creator"
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "db-table-creator"
    spec:
      restartPolicy: "OnFailure"
      securityContext:
        runAsUser: {{ .Values.securityContext.firstParty.uid }}
        runAsGroup: {{ .Values.securityContext.firstParty.gid }}
        fsGroup: {{ .Values.securityContext.firstParty.gid }}
      initContainers:
        - name: "wait-for-database"
          image: "busybox:latest"
          command:
            - "sh"
            - "-c"
            - >-
              until nc -z {{ include "clp.fullname" . }}-database 3306;
                do echo waiting for database;
                sleep 2;
              done
      containers:
        - name: "db-table-creator"
          image: "{{ include "clp.image.ref" . }}"
          imagePullPolicy: "Always"
          env:
            - name: "CLP_DB_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "username"
            - name: "CLP_DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "password"
            - name: "PYTHONPATH"
              value: "/opt/clp/lib/python3/site-packages"
          volumeMounts:
            - name: "config"
              mountPath: "/etc/clp-config.yml"
              subPath: "clp-config.yml"
              readOnly: true
          command: [
            "python3", "-u",
            "-m", "clp_py_utils.create-db-tables",
            "--config", "/etc/clp-config.yml",
            "--storage-engine", {{ .Values.clpConfig.package.storage_engine | quote }}
          ]
      volumes:
        - name: "config"
          configMap:
            name: {{ include "clp.fullname" . }}-config
