apiVersion: "batch/v1"
kind: "Job"
metadata:
  name: {{ include "clp.fullname" . }}-db-table-creator
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "db-table-creator"
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "db-table-creator"
    spec:
      serviceAccountName: {{ include "clp.fullname" . }}-job-watcher
      restartPolicy: "OnFailure"
      securityContext:
        runAsUser: {{ .Values.securityContext.firstParty.uid }}
        runAsGroup: {{ .Values.securityContext.firstParty.gid }}
        fsGroup: {{ .Values.securityContext.firstParty.gid }}
      initContainers:
        - {{- include "clp.waitFor" (dict
            "root" .
            "type" "service"
            "name" "database"
          ) | nindent 10 }}
      containers:
        - name: "db-table-creator"
          image: "{{ include "clp.image.ref" . }}"
          imagePullPolicy: "{{ .Values.image.clpPackage.pullPolicy }}"
          env:
            - name: "CLP_DB_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "username"
            - name: "CLP_DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "password"
            - name: "CLP_DB_ROOT_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "root_username"
            - name: "CLP_DB_ROOT_PASS"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "root_password"
            - name: "PYTHONPATH"
              value: "/opt/clp/lib/python3/site-packages"
          volumeMounts:
            - name: "config"
              mountPath: "/etc/clp-config.yaml"
              subPath: "clp-config.yaml"
              readOnly: true
          command: [
            "python3", "-u",
            "-m", "clp_py_utils.create-db-tables",
            "--config", "/etc/clp-config.yaml",
            "--storage-engine", {{ .Values.clpConfig.package.storage_engine | quote }}
          ]
      volumes:
        - name: "config"
          configMap:
            name: {{ include "clp.fullname" . }}-config
