{{- if .Values.clpConfig.fluent_bit }}
{{- if .Values.clpConfig.fluent_bit.enabled }}
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: {{ include "clp.fullname" . }}-fluent-bit
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "fluent-bit"
{{- end }}
{{- end }}
