apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: {{ include "clp.fullname" . }}-job-watcher
  labels:
    {{- include "clp.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
