{{- if .Values.clpConfig.mcp_server }}
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "clp.fullname" . }}-mcp-server
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "mcp-server"
spec:
  type: {{ .Values.services.type | quote }}
  selector:
    {{- include "clp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "mcp-server"
  ports:
    - port: 8000
      targetPort: "mcp-server"
      {{- if eq .Values.services.type "NodePort" }}
      nodePort: {{ .Values.services.nodePorts.mcpServer }}
      {{- end }}
{{- end }}
