{{- if and .Values.clpConfig.telemetry (not .Values.clpConfig.telemetry.disable) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clp.fullname" . }}-otel-collector
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "otel-collector"
spec:
  ports:
    - name: "otlp-http"
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    {{- include "clp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "otel-collector"
  type: ClusterIP
{{- end }}
