apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: {{ include "clp.fullname" . }}-query-worker-logs
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "query-worker"
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "local-storage"
  selector:
    matchLabels:
      {{- include "clp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "query-worker"
  resources:
    requests:
      storage: "5Gi"
