{{- if has "queue" .Values.clpConfig.bundled }}
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: {{ include "clp.fullname" . }}-queue
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "queue"
spec:
  serviceName: {{ include "clp.fullname" . }}-queue
  replicas: 1
  selector:
    matchLabels:
      {{- include "clp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "queue"
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "queue"
    spec:
      containers:
        - name: "queue"
          image: "rabbitmq:4.2.4"
          imagePullPolicy: "Always"
          env:
            - name: "RABBITMQ_DEFAULT_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-queue
                  key: "username"
            - name: "RABBITMQ_DEFAULT_PASS"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-queue
                  key: "password"
            - name: "RABBITMQ_LOGS"
              value: "-"
            - name: "RABBITMQ_SASL_LOGS"
              value: "-"
          ports:
            - name: "queue"
              containerPort: 5672
          readinessProbe:
            {{- include "clp.readinessProbeTimings" . | nindent 12 }}
            exec: &queue-health-check
              command: ["rabbitmq-diagnostics", "check_running"]
          livenessProbe:
            {{- include "clp.livenessProbeTimings" . | nindent 12 }}
            exec: *queue-health-check
{{- end }}
