apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: {{ include "clp.fullname" . }}-redis
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "redis"
spec:
  serviceName: {{ include "clp.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "clp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "redis"
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "redis"
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.thirdParty.uid }}
        runAsGroup: {{ .Values.securityContext.thirdParty.gid }}
        fsGroup: {{ .Values.securityContext.thirdParty.gid }}
      containers:
        - name: "redis"
          image: "redis:7.2.4"
          imagePullPolicy: "Always"
          env:
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-redis
                  key: "password"
          ports:
            - name: "redis"
              containerPort: 6379
          volumeMounts:
            - name: {{ include "clp.volumeName" (dict
                "component_category" "redis"
                "name" "data"
              ) | quote }}
              mountPath: "/data"
            - name: {{ include "clp.volumeName" (dict
                "component_category" "redis"
                "name" "logs"
              ) | quote }}
              mountPath: "/var/log/redis"
            - name: "config"
              mountPath: "/etc/redis/redis.conf"
              subPath: "redis.conf"
              readOnly: true
          command: [
            "redis-server",
            "/etc/redis/redis.conf",
            "--requirepass", "$(REDIS_PASSWORD)"
          ]
          readinessProbe:
            {{- include "clp.readinessProbeTimings" . | nindent 12 }}
            exec: &redis-health-check
              command: [
                "redis-cli",
                "-h", "127.0.0.1",
                "-p", "6379",
                "-a", "$(REDIS_PASSWORD)",
                "PING"
              ]
          livenessProbe:
            {{- include "clp.livenessProbeTimings" . | nindent 12 }}
            exec: *redis-health-check
      volumes:
        - name: "config"
          configMap:
            name: {{ include "clp.fullname" . }}-config
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: "Delete"
  volumeClaimTemplates:
    - metadata:
        name: {{ include "clp.volumeName" (dict
            "component_category" "redis"
            "name" "data"
          ) | quote }}
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-storage"
        selector:
          matchLabels:
            {{- include "clp.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: "redis"
        resources:
          requests:
            storage: "10Gi"
    - metadata:
        name: {{ include "clp.volumeName" (dict
            "component_category" "redis"
            "name" "logs"
          ) | quote }}
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-storage"
        selector:
          matchLabels:
            {{- include "clp.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: "redis"
        resources:
          requests:
            storage: "5Gi"
