apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "clp-package.fullname" . }}-redis-secret
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
    app.kubernetes.io/component: "redis"
type: "Opaque"
stringData:
  password: {{ .Values.credentials.redis.password | quote }}
