apiVersion: "batch/v1"
kind: "Job"
metadata:
  name: {{ include "clp.fullname" . }}-results-cache-indices-creator
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "results-cache-indices-creator"
spec:
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "results-cache-indices-creator"
    spec:
      serviceAccountName: {{ include "clp.fullname" . }}-service-account
      restartPolicy: "OnFailure"
      {{- if has "results_cache" .Values.clpConfig.bundled }}
      initContainers:
        - {{- include "clp.waitFor" (dict
            "root" .
            "type" "service"
            "name" "results-cache"
          ) | nindent 10 }}
      {{- end }}
      containers:
        - name: "results-cache-indices-creator"
          image: "{{ include "clp.image.ref" . }}"
          imagePullPolicy: "{{ .Values.image.clpPackage.pullPolicy }}"
          env:
            - name: "PYTHONPATH"
              value: "/opt/clp/lib/python3/site-packages"
          command: [
            "python3", "-u",
            "-m", "clp_py_utils.initialize-results-cache",
            "--uri",
            "{{ include "clp.resultsCacheUri" . }}",
            "--stream-collection",
            {{ .Values.clpConfig.results_cache.stream_collection_name | quote }}
          ]
          {{- if .Values.clpConfig.results_cache.tlsVolume }}
          volumeMounts:
            - {{- include "clp.resultsCacheTlsVolumeMount" . | nindent 14 }}
          {{- end }}
      {{- if .Values.clpConfig.results_cache.tlsVolume }}
      volumes:
        - {{- include "clp.resultsCacheTlsVolume" . | nindent 10 }}
      {{- end }}
