apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: {{ include "clp.fullname" . }}-service-account
  labels:
    {{- include "clp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
