{{- if .Values.spider.enabled }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "clp.fullname" . }}-spider-resource-groups
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "compression-coordinator"
type: "Opaque"
stringData:
  compression: {{ .Values.credentials.spiderResourceGroups.compression | quote }}
{{- end }}
