apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: {{ include "clp.fullname" . }}-tmp
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "tmp"
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: "local-storage"
  selector:
    matchLabels:
      {{- include "clp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "tmp"
  resources:
    requests:
      storage: "10Gi"
