{{- if not .Values.clpConfig.telemetry.disable }}
apiVersion: "batch/v1"
kind: "Job"
metadata:
  name: {{ include "clp.fullname" . }}-topology-metrics-emitter
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "topology-metrics-emitter"
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "topology-metrics-emitter"
    spec:
      serviceAccountName: {{ include "clp.fullname" . }}-service-account
      restartPolicy: "OnFailure"
      {{- if has "otel_collector" .Values.clpConfig.bundled }}
      initContainers:
        - {{- include "clp.waitFor" (dict
            "root" .
            "type" "service"
            "name" "otel-collector"
          ) | nindent 10 }}
      {{- end }}
      containers:
        - name: "topology-metrics-emitter"
          image: "{{ .Values.image.curl.repository }}:{{ .Values.image.curl.tag }}"
          imagePullPolicy: {{ .Values.image.curl.pullPolicy | quote }}
          command:
            - "curl"
            - "-s"
            - "--fail"
            - "--retry"
            - "5"
            - "--retry-all-errors"
            - "--retry-delay"
            - "1"
            - "-X"
            - "POST"
            - "-H"
            - "Content-Type: application/json"
            - "-d"
            - {{ include "clp.topologyMetricsPayload" . | quote }}
            - {{ printf "%s/v1/metrics" (include "clp.otelCollectorUrl" .) | quote }}
{{- end }}
