name: "clp-package-presto"

services:
  database:
    extends:
      file: "./docker-compose.base.yaml"
      service: "database"

  queue:
    extends:
      file: "./docker-compose.base.yaml"
      service: "queue"

  redis:
    extends:
      file: "./docker-compose.base.yaml"
      service: "redis"

  results-cache:
    extends:
      file: "./docker-compose.base.yaml"
      service: "results-cache"

  results-cache-indices-creator:
    extends:
      file: "./docker-compose.base.yaml"
      service: "results-cache-indices-creator"

  compose-scheduler:
    extends:
      file: "./docker-compose.base.yaml"
      service: "compose-scheduler"

  compose-worker:
    extends:
      file: "./docker-compose.base.yaml"
      service: "compose-worker"

  webui:
    extends:
      file: "./docker-compose.base.yaml"
      service: "webui"

  garbage-collector:
    extends:
      file: "./docker-compose.base.yaml"
      service: "garbage-collector"
