"""Define all python classes used in `integration-tests`."""

from dataclasses import dataclass, field, InitVar
from pathlib import Path

from tests.utils.utils import (
    remove_path,
    validate_dir_exists,
)


@dataclass(frozen=True)
class ClpCorePathConfig:
    """Path configuration for the CLP core binaries."""

    #: Root directory containing all CLP core binaries.
    clp_core_bins_dir: Path

    def __post_init__(self) -> None:
        """
        Validates that the CLP core binaries directory exists and contains all required
        executables.
        """
        clp_core_bins_dir = self.clp_core_bins_dir
        validate_dir_exists(clp_core_bins_dir)

        required_binaries = [
            "clg",
            "clo",
            "clp",
            "clp-s",
            "indexer",
            "log-converter",
            "reducer-server",
        ]
        missing_binaries = [b for b in required_binaries if not (clp_core_bins_dir / b).is_file()]
        if len(missing_binaries) > 0:
            err_msg = (
                f"CLP core binaries at {clp_core_bins_dir} are incomplete."
                f" Missing binaries: {', '.join(missing_binaries)}"
            )
            raise RuntimeError(err_msg)

    @property
    def clp_binary_path(self) -> Path:
        """:return: The absolute path to the core binary `clp`."""
        return self.clp_core_bins_dir / "clp"

    @property
    def clp_s_binary_path(self) -> Path:
        """:return: The absolute path to the core binary `clp-s`."""
        return self.clp_core_bins_dir / "clp-s"

    @property
    def log_converter_binary_path(self) -> Path:
        """:return: The absolute path to the core binary `log-converter`."""
        return self.clp_core_bins_dir / "log-converter"


@dataclass(frozen=True)
class PackageCompressionJob:
    """A compression job for a package test."""

    #: The absolute path to the dataset (either a file or directory).
    path_to_original_dataset: Path

    #: Options to specify in the compression command.
    options: list[str] | None

    #: Positional arguments to specify in the compression command (do not put paths to compress)
    positional_args: list[str] | None


@dataclass(frozen=True)
class IntegrationTestPathConfig:
    """Path configuration for CLP integration tests."""

    #: Default directory for integration test output.
    test_root_dir: Path

    #: Directory to store the downloaded logs.
    logs_download_dir: Path = field(init=False, repr=True)

    #: Optional initialization value used to set `logs_download_dir`.
    logs_download_dir_init: InitVar[Path | None] = None

    def __post_init__(self, logs_download_dir_init: Path | None) -> None:
        """Initialize and create required directories for integration tests."""
        if logs_download_dir_init is not None:
            object.__setattr__(self, "logs_download_dir", logs_download_dir_init)
        else:
            object.__setattr__(self, "logs_download_dir", self.test_root_dir / "downloads")

        self.test_root_dir.mkdir(parents=True, exist_ok=True)
        self.logs_download_dir.mkdir(parents=True, exist_ok=True)


@dataclass(frozen=True)
class IntegrationTestLogs:
    """Metadata for the downloaded logs used for integration tests."""

    #:
    name: str
    #:
    tarball_url: str
    integration_test_path_config: InitVar[IntegrationTestPathConfig]
    #:
    tarball_path: Path = field(init=False, repr=True)
    #:
    extraction_dir: Path = field(init=False, repr=True)
    #: Optional number of log events in the downloaded logs.
    num_log_events: int | None = None

    def __post_init__(self, integration_test_path_config: IntegrationTestPathConfig) -> None:
        """Initialize and set tarball and extraction paths for integration test logs."""
        name = self.name.strip()
        if 0 == len(name):
            err_msg = "`name` cannot be empty."
            raise ValueError(err_msg)
        logs_download_dir = integration_test_path_config.logs_download_dir
        validate_dir_exists(logs_download_dir)

        object.__setattr__(self, "name", name)
        object.__setattr__(self, "tarball_path", logs_download_dir / f"{name}.tar.gz")
        object.__setattr__(self, "extraction_dir", logs_download_dir / name)


@dataclass(frozen=True)
class CompressionTestPathConfig:
    """Per-test path configuration for compression workflow artifacts."""

    #:
    test_name: str
    #: Directory containing the original (uncompressed) log files used by this test.
    logs_source_dir: Path
    integration_test_path_config: InitVar[IntegrationTestPathConfig]
    #: Path to store compressed archives generated by the test.
    compression_dir: Path = field(init=False, repr=True)
    #: Path to store decompressed logs generated by the test.
    decompression_dir: Path = field(init=False, repr=True)

    def __post_init__(self, integration_test_path_config: IntegrationTestPathConfig) -> None:
        """Initialize and set required directory paths for compression tests."""
        test_name = self.test_name.strip()
        if 0 == len(test_name):
            err_msg = "`test_name` cannot be empty."
            raise ValueError(err_msg)
        test_root_dir = integration_test_path_config.test_root_dir
        validate_dir_exists(test_root_dir)

        object.__setattr__(self, "test_name", test_name)
        object.__setattr__(self, "compression_dir", test_root_dir / f"{test_name}-archives")
        object.__setattr__(
            self, "decompression_dir", test_root_dir / f"{test_name}-decompressed-logs"
        )

    def clear_test_outputs(self) -> None:
        """Remove any existing output directories created by this compression test."""
        remove_path(self.compression_dir)
        remove_path(self.decompression_dir)


@dataclass(frozen=True)
class ConversionTestPathConfig:
    """Per-test path configuration for conversion workflow artifacts."""

    #:
    test_name: str
    #: Directory containing the original (uncompressed) log files used by this test.
    logs_source_dir: Path
    integration_test_path_config: InitVar[IntegrationTestPathConfig]
    #: Path to store converted kv-ir files generated by the test.
    conversion_dir: Path = field(init=False, repr=True)
    #: Path to store compressed archives generated by the test.
    compression_dir: Path = field(init=False, repr=True)
    #: Optional number of log events in the converted logs.
    num_log_events: int | None = None

    def __post_init__(self, integration_test_path_config: IntegrationTestPathConfig) -> None:
        """Initialize and set required directory paths for conversion tests."""
        test_name = self.test_name.strip()
        if 0 == len(test_name):
            err_msg = "`test_name` cannot be empty."
            raise ValueError(err_msg)
        test_root_dir = integration_test_path_config.test_root_dir
        validate_dir_exists(test_root_dir)

        object.__setattr__(self, "test_name", test_name)
        object.__setattr__(self, "conversion_dir", test_root_dir / f"{test_name}-converted")
        object.__setattr__(self, "compression_dir", test_root_dir / f"{test_name}-archives")

    def clear_test_outputs(self) -> None:
        """Remove any existing output directories created by this conversion test."""
        remove_path(self.conversion_dir)
        remove_path(self.compression_dir)
