name: "clp-core-build-containers"
description: "Builds and publishes container images for CLP-core's dependencies"

inputs:
  image_name:
    description: "Name of the image (without registry or repository) to create"
    required: true
  docker_context:
    description: "The context directory for Docker when building the image"
    required: true
  docker_file:
    description: "The Dockerfile to use to build the image"
    required: true
  push_deps_image:
    description: "Whether to publish a container image containing CLP's dependencies"
    required: true
  token:
    description: "Registry token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: "docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2"

    - if: "inputs.push_deps_image == 'true'"
      uses: "docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772"
      with:
        registry: "ghcr.io"
        username: "${{github.actor}}"
        password: "${{inputs.token}}"

    - id: "get_image_props"
      shell: "bash"
      run: |
        if [[ "${{inputs.push_deps_image}}" == "true" ]] ; then
          # Docker doesn't support repository names with uppercase characters, so we convert to
          # lowercase here.
          repository=$(echo '${{github.repository}}' | tr '[:upper:]' '[:lower:]')

          echo "qualified_image_name=ghcr.io/${repository}/${{inputs.image_name}}" \
            >> "$GITHUB_OUTPUT"
          echo "branch=${{github.ref_name}}" >> "$GITHUB_OUTPUT"
          echo "output=type=registry" >> "$GITHUB_OUTPUT"
        else
          image_path="/tmp/${{inputs.image_name}}.tar"
          echo "image_path=${image_path}" >> "$GITHUB_OUTPUT"

          echo "qualified_image_name=${{inputs.image_name}}" >> "$GITHUB_OUTPUT"
          echo "branch=latest" >> "$GITHUB_OUTPUT"
          echo "output=type=docker,dest=${image_path}" >> "$GITHUB_OUTPUT"
        fi

    - id: "deps_image_meta"
      uses: "docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804"
      with:
        images: "${{steps.get_image_props.outputs.qualified_image_name}}"
        tags: |
          type=raw,value=${{steps.get_image_props.outputs.branch}}

    - uses: "docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4"
      with:
        context: "${{inputs.docker_context}}"
        file: "${{inputs.docker_file}}"
        labels: "${{steps.deps_image_meta.outputs.labels}}"
        tags: "${{steps.deps_image_meta.outputs.tags}}"
        outputs: "${{steps.get_image_props.outputs.output}}"

    - if: "inputs.push_deps_image == 'false'"
      uses: "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02"
      with:
        name: "${{steps.get_image_props.outputs.qualified_image_name}}"
        path: "${{steps.get_image_props.outputs.image_path}}"
        retention-days: 1
