receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: "10s"
    send_batch_size: 5000

exporters:
  clickhouse:
    endpoint: "tcp://clickhouse:9000"
    database: "clp_telemetry"
    username: "default"
    password: "clickhouse"
    ttl: "2160h"
    metrics_table_name: "otel_metrics"
    traces_table_name: "otel_traces"
    logs_table_name: "otel_logs"

service:
  pipelines:
    metrics:
      receivers: ["otlp"]
      processors: ["batch"]
      exporters: ["clickhouse"]
