[package]
name = "search-coordinator"
version = "0.13.1-dev"
edition = "2024"

[[bin]]
name = "search-coordinator"
path = "src/bin/search_coordinator.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.6.4", features = ["derive"] }
clp-rust-utils = { path = "../clp-rust-utils" }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread", "signal", "time"] }
tokio-util = "0.7.18"
tracing = "0.1.44"
