name: CLP Base Image Build
on:
  push:
    branches:
      - main
    paths:
      - 'tools/packager/docker-base/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}/clp-base-x86-ubuntu-focal

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build Image
    steps:
      - name: Checkout
        uses: actions/Checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: tools/packager/docker-base/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      