name: "clp-docs-macos"

on:
  pull_request:
  push:
  schedule:
    # Run daily at 00:15 UTC (the 15 is to avoid periods of high load)
    - cron: "15 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  build-macos:
    if: "vars.GH_DISABLE_MACOS != 'true'"
    name: "build-macos"
    runs-on: "macos-15"
    permissions:
      # To check out the repository.
      contents: "read"
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"  # v6.0.2
        with:
          persist-credentials: false
          lfs: "true"
          submodules: "recursive"

      - uses: "./tools/yscope-dev-utils/exports/github/actions/install-python"

      - uses: "./tools/yscope-dev-utils/exports/github/actions/install-go-task"
        with:
          version: "3.48.0"

      - name: "Build docs"
        shell: "bash"
        run: "task docs:site"
