name: "clp-integration-tests"

on:
  pull_request:
    paths-ignore: &ignored_paths
      - ".github/*"
      - ".github/ISSUE_TEMPLATE/**"
      - "docs/**"
  push:
    paths-ignore: *ignored_paths
  schedule:

    # Run daily at 00:30 UTC (the 30 is to avoid periods of high load)
    - cron: "30 0 * * *"
  workflow_dispatch:

env:
  DEPS_IMAGE_NAME_PREFIX_X86: "clp-core-dependencies-x86-"
  OS_NAME: "ubuntu-jammy"

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency; exclude the `main` branch.
  cancel-in-progress: "${{github.ref != 'refs/heads/main'}}"

jobs:
  integration-tests:
    name: "integration-tests"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"  # v6.0.2
        with:
          submodules: "recursive"

      - name: "Work around actions/runner-images/issues/6775"
        run: "chown $(id -u):$(id -g) -R ."
        shell: "bash"

      # Run the integration tests inside the published `ubuntu-jammy` dependencies image.
      - name: "Build package and run integration tests"
        uses: "./.github/actions/run-on-image"
        with:
          image_name: "${{env.DEPS_IMAGE_NAME_PREFIX_X86}}${{env.OS_NAME}}"

          # Use the published `main` image.
          use_published_image: "true"
          run_command: >-
            CLP_CPP_MAX_PARALLELISM_PER_BUILD_TASK=$(getconf _NPROCESSORS_ONLN)
            HOME=/tmp
            task tests:integration
